### ISSUE TITLE
Equal Silhouette measure

### ISSUE THREAD

**Issue by rogerkuou** [phenology/cgc#41]
When the same Silhouette measure occurs to multiple k values (although this is very unlikely, but not theoretically impossible), the smallest number of k should be selected.

**Comment by rogerkuou** [comment]
The max silhouette value is selected by `idx_k = np.argmax(silhouette_avg_list)`, which returns the first elements since `r_range` is forced to be sorted.

**Comment by fnattino** [comment]
So this mean this will be fixed already when merging #44 - right?
