### ISSUE TITLE
Is the numerical parameter `epsilon` really necessary?

### ISSUE THREAD

**Issue by fnattino** [phenology/cgc#49]
One could use `np.divide(num, dem, where=(dem != 0))` and similarly for the `log`.

**Comment by fnattino** [comment]
**Long Issue Description**

In the current version of the algorithm the `epsilon` parameter is employed in two steps:
* when computing the co-cluster average matrix (`CoCavg`), to avoid zero-division errors.
* when computing the loss function, to avoid zero arguments in the logarithm expression.
 
With respect to the usage of `epsilon` as in the first point, the current algorithm implementation is more or less the following:

```python
# Z - (m x n) data matrix
# R - (m x k) row cluster assignment matrix (with k row clusters)
# C - (m x l) row cluster assignment matrix (with l row clusters)
# nel_clusters - (k x l) matrix with number of elements in each co-clusters

Gavg = Z.mean()

CoCavg = np.dot(np.dot(R.T, Z), C)  # CoCavg[i,j] is now the sum of all elemnts assigned to the co-cluster (i, j)
CoCavg += Gavg * epsilon
CoCavg /= nel_clusters + epsilon
```

The code reflects the [original Matlab code](http://www.ideal.ece.utexas.edu/software.html) (file `coclust_idiv.m`):

```Matlab
% get data matrix size and fixed averages
[m, n] = size(Z); 
Y =W.*Z;
Em = ones(m,1);
En = ones(n,1);
Gavg = (Em'*Y*En)/(Em'*W*En);
...
CoCavg = (R'*Y*C +Gavg*epsilon)./(R'*W*C +epsilon);
``` 

So, the current implementation adds a small number to the numerator (`Gavg*epsilon`, where `epsilon` is by defaut 1.E-8) and a small number to the denominator (`epsilon`), before carrying out the division. This is fine whenever all co-clusters are populated, but a strange behaviour actually occurs for empty clusters, whose co-cluster average is assigned to `(0 + Gavg*epsilon)/(0 + epsilon) = Gavg*epsilon/epsilon = Gavg`, i.e. the average of all elements in the matrix. 

**Example**: 

```python
import numpy as np

# data matrix
Z = np.array([
    [1, 1, 1, 2, 2, 3],
    [1, 1, 1, 2, 2, 3],
    [4, 4, 4, 5, 5, 6],
    [4, 4, 4, 7, 7, 8],
]).astype(float)

# number of clusters
nclusters_row = 4
nclusters_col = 5

# cluster assignment
row_clusters = np.array([0, 0, 1, 3])
col_clusters = np.array([0, 0, 0, 1, 1, 3])
```

Using the currently implemented algorithm to compute `CoCavg` in the coclustering module, one obtains:
```
array([[1.        , 2.        , 3.41666667, 3.        , 3.41666667],
       [4.        , 4.99999999, 3.41666667, 5.99999997, 3.41666667],
       [3.41666667, 3.41666667, 3.41666667, 3.41666667, 3.41666667],
       [4.        , 6.99999998, 3.41666667, 7.99999995, 3.41666667]])
```
.. while the correct matrix of cocluster average should be:
```
array([[ 1.,  2., nan,  3., nan],
       [ 4.,  5., nan,  6., nan],
       [nan, nan, nan, nan, nan],
       [ 4.,  7., nan,  8., nan]])
```

**Discussion**

The presence of the term`Gavg*epsilon` at the numerator in the co-cluster mean expression has consequences on the co-clustering algorithm: empty clusters are never really treated as empty clusters, since they are assigned a co-cluster average that is non-zero. In fact, when looking for which row cluster to assign each element in order to minimise the loss function,  empty clusters are dealt with as clusters whose average is equal to the mean over all elements, which is incorrect. As a result, clusters that are left empty at a given iteration can become again populated at later iterations (I have observed this in few occasions).  I guess this might lead to slow convergence in some cases and potentially also to slightly different results? 

Note that the [original paper](https://jmlr.org/papers/volume8/banerjee07a/banerjee07a.pdf) does not mention anything similar to the term `Gavg*epsilon` neither in the theory section nor in the Appendix E, which provides the recipes for implementations. I thus suggest to remove this term altogether while removing `epsilon` , the use of which could be rather easily bypassed (see comment above) with the benefit of removing one numerical parameter.

**Comment by rzuritamilla** [comment]
Hi @fnattino, thank you for the detailed description of the issue (and, of course, for your critical analysis of the algorithm!!). I agree with your assessment: epsilon is not needed and might actually have a negative impact on the convergence and results. At first I thought that having a CoCavg matrix with NaNs could be problematic but the rows and columns with NaNs correspond to empty clusters so the _min_dist_ functions will not suffer from the proposed change.

**Comment by EIzquierdo** [comment]
Hi @fnattino and @rzuritamilla , I was reading the problem and sorry, it was my fault. When I started to work with the co-clustering and implemet the tri-clustering, I noted that sometimes gave me an error (NaNs in the matrices). Therefore my faster solution was add the epsilon (didn't see the consequences that I see now). For that reason, there is not information in the original paper. Also because for them, if I'm not wrong, it could not have empty clusters.
I think it is a right solution.

**Comment by fnattino** [comment]
Thanks @rzuritamilla and @EIzquierdo for taking the time to have a look! And happy to hear that you agree in that `epsilon` can be safely removed. @EIzquierdo : no worries, actually the usage of `epsilon` here seems to originate from the code from the original Bregman co-clustering publication (Banerjee et al., JMLR 2007): http://www.ideal.ece.utexas.edu/software.html
