### ISSUE TITLE
k-means centroids

### ISSUE THREAD

**Issue by fnattino** [phenology/cgc#50]
Centroids returned by the k-means refinement step are averages of the cluster averages. Should one instead return averages computed over all elements of the clusters that are being merged?

**Comment by rogerkuou** [comment]
Smaller clusters are weighted as the same as the big clusters. This centroids is a bit useless infomation for users. The statistics need to be re-calculated over the refined cluster.

This should not be named "centroids". Should be "mean of the refined cluster"
