### ISSUE TITLE
k-means should return cluster labels

### ISSUE THREAD

**Issue by fnattino** [phenology/cgc#52]
The k-means refinement currently returns the cluster centroids. It would be helpful if it would return also a mapping of the co- or tri-clusters to the refined cluster labels.

**Comment by rogerkuou** [comment]
Unpack the k-mean labels to a dict: {refined_label: [(band_label0, row_label0, col_label0), (band_label1, row_label1, col_label1), ...]}, stored in kmean_results.

**Comment by rogerkuou** [comment]
Linked to #50
