### ISSUE TITLE
Minor repository improvements

### ISSUE THREAD

**Issue by fnattino** [phenology/cgc#63]
- [x] Repository `README` file:
	- Add statement of need: “The authors should clearly state what problems the software is designed to solve and who the target audience is.”
	- Mention what can be found in documentation: example usages (links), API documentation. 
	- Link the tutorial
- [x] Add small example to main object docstrings: `Coclustering`, `Kmeans`, `Triclustering`

**Comment by rogerkuou** [comment]
Solved in PR #66
