### ISSUE TITLE
Failing test: `test_mem_estimate_coclustering_numpy`

### ISSUE THREAD

**Issue by fnattino** [phenology/cgc#76]
@Narayana-Rao, thanks again for [your feedback](https://github.com/openjournals/joss-reviews/issues/4032#issuecomment-1012194082) on the package. 

Concerning your point (2): we have not been able to reproduce the test failure that you observe, and while we have [fixed an issue](https://github.com/phenology/cgc/pull/75) with the same unit test, this seems to be unrelated to the error that you report. We have tried different OSs and Python versions, which we also test in our [continuous integration workflow](https://github.com/phenology/cgc/blob/master/.github/workflows/build.yml), were all tests are passing. Could you please provide some details about your setup, e.g. OS/python version/environment? Thank you so much in advance!

**Comment by Narayana-Rao** [comment]
@fnattino, I have rerun the tests on Mac, Ubuntu and Windows 11. I didn't see any issue with mac and ubuntu. However, the same error is repeated in windows OS. Please check the attached log.txt for the details. 
[log.txt](https://github.com/phenology/cgc/files/8136550/log.txt)
.

**Comment by fnattino** [comment]
Thank you so much for the log @Narayana-Rao , this is now fixed!
